app: sw4rtz-it-app
org: wagnernicolas1
service: sw4rtz-it

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

functions:
  app:
    handler: handler.server
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true

resources: # CloudFormation template syntax from here on.
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Arxweave
        AttributeDefinitions:
          - AttributeName: arXivID
            AttributeType: S
        KeySchema:
          - AttributeName: arXivID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25